manifest:
  remotes:
    - name: ergohaven
      url-base: https://github.com/ergohaven
    - name: badjeff
      url-base: https://github.com/badjeff
  projects:
    - name: ergohaven-zmk
      remote: ergohaven
      revision: main
      import: config/west.yml
    - name: zmk-pmw3610-driver
      remote: badjeff
      revision: main
  self:
    path: config