manifest:
  remotes:
    - name: ergohaven
      url-base: https://github.com/ergohaven
    - name: oleksandrmaslov
      url-base: https://github.com/oleksandrmaslov
    - name: kjtvfvrndr-sketch
      url-base: https://github.com/kjtvfvrndr-sketch
  projects:
    - name: ergohaven-zmk
      remote: ergohaven
      revision: main
      import: config/west.yml
    - name: zmk-pmw3610-driver
      remote: kjtvfvrndr-sketch
      revision: diag-shutdown
    - name: zmk-pointing-acceleration
      remote: oleksandrmaslov
      revision: main
    - name: zmk-temp-layer-keep
      remote: kjtvfvrndr-sketch
      revision: main
  self:
    path: config