CONFIG_ZMK_POINTING=y
CONFIG_SPI=y
CONFIG_INPUT=y

CONFIG_USB_HID_POLL_INTERVAL_MS=1

# CONFIG_BT_PERIPHERAL_PREF_MIN_INT=9    # 11.25 мс
# CONFIG_BT_PERIPHERAL_PREF_MAX_INT=12   # 15 мс

CONFIG_PMW3610_ALT=y
CONFIG_PMW3610_ALT_SMART_ALGORITHM=y
CONFIG_PMW3610_ALT_REPORT_INTERVAL_MIN=16
CONFIG_PMW3610_ALT_INIT_POWER_UP_EXTRA_DELAY_MS=2000
CONFIG_PMW3610_ALT_REST1_SAMPLE_TIME_MS=100
CONFIG_PMW3610_ALT_REST2_SAMPLE_TIME_MS=200
CONFIG_PMW3610_ALT_REST3_SAMPLE_TIME_MS=300
CONFIG_PMW3610_ALT_RUN_DOWNSHIFT_TIME_MS=2000
CONFIG_PMW3610_ALT_REST1_DOWNSHIFT_TIME_MS=3000
CONFIG_PMW3610_ALT_REST2_DOWNSHIFT_TIME_MS=30000